import type { LearningPlan, PlanItem, TrackerState } from "./types";

/** Serialize a plan to clean Markdown for download/sharing. */
export function planToMarkdown(plan: LearningPlan, tracker: TrackerState): string {
  const lines: string[] = [];
  lines.push(`# LearnX plan — ${plan.role}`);
  if (plan.company) lines.push(`**Target:** ${plan.company}`);
  lines.push(`**Goals:** ${plan.goals.join(" · ")}`);
  lines.push("");
  lines.push("## Company & team research");
  for (const line of plan.companyResearch) lines.push(`- ${line}`);
  lines.push("");
  lines.push("## Skill gap");
  for (const gap of plan.skillGaps) lines.push(`- **${gap.skill}** — ${gap.status}. ${gap.note}`);
  lines.push("");
  for (const phase of plan.phases) {
    lines.push(`## ${phase.title}`);
    lines.push(phase.summary);
    lines.push("");
    for (const item of phase.items) {
      lines.push(`### ${tracker[item.id] ? "[x]" : "[ ]"} ${item.title} (~${item.estimatedHours}h)`);
      lines.push(item.why);
      for (const r of item.resources) {
        lines.push(`- [${r.title}](${r.url}) — ${r.provider}${r.certNote ? ` — 🏅 ${r.certNote}` : ""}`);
      }
      lines.push("");
    }
  }
  if (plan.interviewPrep?.length) {
    lines.push("## Interview prep");
    for (const tip of plan.interviewPrep) lines.push(`- ${tip}`);
  }
  lines.push("");
  lines.push(`_Generated by LearnX — free resources only, links verified._`);
  return lines.join("\n");
}

/**
 * "This week" as an .ics calendar: one all-day event per item on consecutive
 * days starting tomorrow. All-day events keep timezone handling trivial and
 * import cleanly into Google/Apple/Outlook.
 */
export function thisWeekToICS(items: PlanItem[], role: string): string {
  const pad = (n: number) => String(n).padStart(2, "0");
  const fmt = (d: Date) => `${d.getFullYear()}${pad(d.getMonth() + 1)}${pad(d.getDate())}`;
  const esc = (s: string) => s.replace(/\\/g, "\\\\").replace(/;/g, "\\;").replace(/,/g, "\\,");

  const events = items.map((item, i) => {
    const start = new Date();
    start.setDate(start.getDate() + 1 + i);
    const end = new Date(start);
    end.setDate(end.getDate() + 1);
    return [
      "BEGIN:VEVENT",
      `UID:learnx-${item.id}-${fmt(start)}@learnx`,
      `DTSTAMP:${fmt(new Date())}T000000Z`,
      `DTSTART;VALUE=DATE:${fmt(start)}`,
      `DTEND;VALUE=DATE:${fmt(end)}`,
      `SUMMARY:${esc(`LearnX: ${item.title} (~${item.estimatedHours}h)`)}`,
      `DESCRIPTION:${esc(`${item.why} — part of your "${role}" plan on LearnX.`)}`,
      "END:VEVENT",
    ].join("\r\n");
  });

  return ["BEGIN:VCALENDAR", "VERSION:2.0", "PRODID:-//LearnX//Plan//EN", ...events, "END:VCALENDAR"].join("\r\n");
}

export function downloadFile(filename: string, content: string, mime: string): void {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
